config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :products, only: :show

  namespace :seller do
    resources :products
  end

  post '/populate', to: 'orders#populate', as: :populate_orders
  resources :orders, only: [:index, :update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :variant

  def item_name
    variant.product.name
  end

  def item_description
    variant.product.description
  end
  
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :line_items
  enum status: { created: 'Created', cancelled: 'Cancelled' }

  before_create :assign_number, :update_status

  def add_items(params)
    self.line_items.new(variant_id: params[:variant_id], item_count: params[:quantity], price: params[:price])
    self.save
  end

  def cancelable
    (Time.now - created_at) < 24.hours 
  end

  private

    def assign_number
      self.number = "SM-#{Time.now.sec * 1000}-#{SecureRandom.hex(3)}"
    end

    def update_status
      self.status = 'Created'
    end

end

app/models/product.rb
class Product < ApplicationRecord

  before_create :add_slug
  
  has_many :variants

  accepts_nested_attributes_for :variants

  def image_url
    '/images/no-image.png'
  end

  private

    def add_slug
      self.slug = self.name.downcase.split(' ').join('-')
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :orders
  
  def seller?
    self.role_id == 1
  end

end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :mobile, :role_id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!
  before_action :current_order, only: :populate
  before_action :find_order, only: [:edit, :update]
  
  def index
    @orders = current_user.orders
  end

  def edit
  end

  def populate
    if @current_order.add_items(params)
      session[:order_id] = @current_order.number
      redirect_to orders_url, notice: 'Item successfully added into cart'
    else
      redirect_to root_url, notice: 'Something went wrong'
    end
  end

  def update
    if @order.update_column(:status, Order.statuses[:cancelled])
      redirect_to orders_url, notice: 'Order successfully cancelled'
    else
      redirect_to orders_url, notice: @order.errors.full_messages.join('<br/>')
    end
  end

  private

    def current_order
      if session[:order_id].present?
        @current_order ||= current_user.orders.find_by_number(session[:order_id])
      else
        @current_order ||= current_user.orders.new
      end
    end

    def find_order
      @order = current_user.orders.find_by_number(params[:id])
      if @order.blank?
        redirect_to root_url, notice: 'Order not found'
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:show]

  def show
  end

  private

    def find_product
      @product = Product.where(slug: params[:id]).includes(:variants).first
      if @product.blank?
        redirect_to root_url, notice: 'Product not found'
      end
    end
end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < Seller::StoreController

  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @products = current_user.products
  end

  def new
    @product = Product.new
  end

  def edit
    @product.variants.build
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to edit_seller_product_url(@product.slug), notice: 'Product successfully created'
    else
      flash[:error] = @product.errors.full_messages.join('<br/>')
      render action: :new
    end
  end

  def update
    if @product.update_attributes product_params
      redirect_to edit_seller_product_url(@product.slug), notice: 'Product updated successfully'
    else
      flash[:error] = @product.errors.full_messages.join('<br/>')
      render action: :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to seller_products_url, notice: 'Product deleted successfully'
  end

  private

    def product_params
      params.require(:product).permit(:name, :slug, :base_price, variants_attributes: [:id, :color, :price, :product_id, :count_on_hand])
    end

    def find_product
      @product = current_user.products.find_by_slug(params[:id])
      if @product.blank?
        redirect_to seller_products_url, notice: 'Product not found'
      end
    end
end

app/controllers/seller/store_controller.rb
class Seller::StoreController < ApplicationController
  before_action :authenticate_user!
  before_action :autherize_user

  protected

    def autherize_user
      unless current_user.seller?
        redirect_to root_url, notice: 'You are not autherize to access this page'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.section
.row
  - if @products.present?
    - @products.each do |product|
      = render partial: '/shared/product', locals: { product: product }
  - else
    .col-xs-12
      .center-image
        = image_tag '/images/noresult.png', class: 'img-responsive no-product'

app/views/layouts/_header.html.slim
header.header
  .container
    .row
      .col-xs-2
        = link_to root_url, class: 'txt-white' do
          span ShopMe
      .col-xs-10
        .info.pull-right
          - if user_signed_in?
            ul.txt-white
              li
                = current_user.name
                '
                span.fa.fa-caret-down
                ul#dropdown
                  - if current_user.seller?
                    li
                      = link_to seller_products_url do
                        span.fa.fa-university
                        '
                        span Store
                  - else
                    li
                      = link_to orders_url do
                        span.fa.fa-list
                        '
                        span Orders
                  li
                    = link_to destroy_user_session_url, method: :delete  do
                      span.fa.fa-power-off
                      '
                      span Log out
          - else
            = link_to "Sign in", new_user_session_url, class: 'txt-white'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Shop me
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render partial: 'layouts/header'
    .container
      = yield

app/views/orders/index.html.slim
.section
.row
  .col-xs-12
    - if @orders.present?
      - @orders.each do |order|
        table.table.table-responsive.table-striped
          thead
            tr
              th Item Description
              th
              th
          tbody
            - order.line_items.each do |line_item|
              tr
                td colspan="2"
                  = image_tag line_item.variant.product.image_url, class: 'img-responsive img-small'
                td
                  b= order.status.humanize
                  br
                  b= line_item.item_name
                  br
                  p= line_item.item_description
                  br
                  span.fa.fa-rupee
                  '
                  span= line_item.price.to_f
                td
                  - if order.cancelable && order.status != 'cancelled'
                    = link_to 'Cancel order', order_url(order.number), method: :put, class: 'btn btn-danger'
            

app/views/products/_cart_form.html.slim
.cart-details
  = form_tag populate_orders_path, class: 'form-horizontal', method: :post do |f|
    .row
      .col-md-6.col-xs-12
        = hidden_field_tag :price, @product.variants.first.price
        = label_tag :color, 'Select a color', class: 'control-label'
        = select_tag :variant_id, options_for_select(@product.variants.pluck(:color, :id), @product.variants.first.id), { class: 'form-control' }
      .col-md-6.col-xs-12
        = label_tag :quantity, 'Quantity', class: 'control-label'
        = number_field_tag :quantity, 1, min: 1, class: 'form-control'
    .row
      .section
      .col-xs-12
        = submit_tag 'Buy now', class: 'btn btn-primary'

app/views/products/show.html.slim
.section
.row
  .col-sm-8.col-xs-12
    .image-display-section
      .large-image
        = image_tag @product.image_url, class: 'img-responsive'
  .col-sm-4.col-xs-12
    .product-details
      .name-details
        b= @product.name
        p= @product.description
      #price-section
        span.fa.fa-rupee
        '
        span#price
          b= @product.base_price.to_f
      
      = render partial: 'cart_form'

app/views/seller/products/_form.html.slim
- url = @product.new_record? ? seller_products_path : seller_product_path(@product.slug)
= nested_form_for @product, url: url, html: { class: "form form-horizontal product" } do |f|
  .col-lg-6
    = f.label :name, :class => 'control-label'
    = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .col-lg-6
    = f.label :base_price, :class => 'control-label'
    = f.text_field :base_price, :class => 'form-control'
    = f.error_span(:base_price)
  .col-lg-12#variants-div
    = f.fields_for :variants do |vf|
      .row
        .col-lg-6
          = vf.hidden_field :id
          = vf.label :color, class: 'control-label'
          = vf.text_field :color, class: 'form-control'
        .col-lg-6
          = vf.label :price, class: 'control-label'
          = vf.text_field :price, class: 'form-control'
      .row  
        .col-lg-6
          = vf.label :count_on_hand, class: 'control-label'
          = vf.text_field :count_on_hand, class: 'form-control'
  .col-lg-12
    = f.link_to_add 'Add variant', :variants 
  .col-lg-12
    .section
    .pull-left
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), seller_products_path, :class => 'btn'

app/views/seller/products/edit.html.slim
- model_class = Product
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/seller/products/index.html.slim
- model_class = Product
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:slug)
      th= model_class.human_attribute_name(:base_price)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @products.each do |product|
      tr
        td= link_to product.id, seller_product_path(product.slug)
        td= product.name
        td= product.slug
        td= product.base_price
        td=l product.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_seller_product_path(product.slug), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), seller_product_path(product.slug), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_seller_product_path, :class => 'btn btn-primary'

app/views/seller/products/new.html.slim
- model_class = Product
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/seller/products/show.html.slim
- model_class = Product
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @product.name
p
  strong= model_class.human_attribute_name(:slug) + ':'
  br
  = @product.slug
p
  strong= model_class.human_attribute_name(:base_price) + ':'
  br
  = @product.base_price

= link_to t('.back', :default => t("helpers.links.back")), seller_products_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_seller_product_path(@product.slug), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), seller_product_path(@product.slug), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/shared/_product.html.slim
.col-md-3.col-sm-4.col-xs-6
  = link_to product_url(product.slug) do
    .product-container
      .img-container
        = image_tag product.image_url, class: 'img-responsive'
      .details-container
        .row
          .col-sm-8.col-xs-12.name-details
            = product.name
          .col-sm-4.col-xs-12.price-details
            span.fa.fa-rupee
            '
            = product.base_price.to_f